In [1]:
#numpy处理线性代数的问题
#矩阵乘法，矩阵分解，行列式以及其他方阵函数等

In [4]:
import numpy as np

In [6]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])

In [8]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [9]:
y=np.array([[6,23.],[-1,7],[8,9]])

In [10]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [11]:
#矩阵乘法

In [13]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [14]:
np.dot(x,y)

array([[  28.,   64.],
       [  67.,  181.]])